### ISSUE TITLE
RuleBasedTokenizer shouldn't write to stderr

### ISSUE THREAD

**Issue by jsichi** [ixa-ehu/ixa-pipe-ml#5]
This line should be wrapped in an if (DEBUG) conditional:

https://github.com/ixa-ehu/ixa-pipe-ml/blob/f7e6eff41e1314ee2bf413e343960157893be890/src/main/java/eus/ixa/ixa/pipe/ml/tok/RuleBasedTokenizer.java#L249

As it is, stderr spews when the tokenizer is called repeatedly.

**Comment by ragerri** [comment]
Fixed. Do you need a maven central release?

**Comment by jsichi** [comment]
Thanks.  I'm currently using an ugly thread-unsafe workaround (wrap calls with stderr redirect), so if you can do a maven central release before end of year, that would be awesome.

**Comment by ragerri** [comment]
done
